
const partnerslogo = [
    { id: 1, name: "Microsoft", logo: "/images/PartnerLogo/Microsoft.png" },
    { id: 2, name: "HDFC Bank", logo: "/images/PartnerLogo/HDFC_Bank_Logo.png" },
    { id: 3, name: "Tata Motors", logo: "/images/PartnerLogo/Tata-Motors.png" },
    { id: 4, name: "Zee Studios", logo: "/images/PartnerLogo/Zee_Studios_logo.png" },
    { id: 5, name: "Livspace", logo: "/images/PartnerLogo/Livspace.png" },
    { id: 6, name: "Acer", logo: "/images/PartnerLogo/Acer.png" },
    { id: 7, name: "HCL Technologies", logo: "/images/PartnerLogo/HCL_Technologies_logo.png" },
    { id: 8, name: "eClerx", logo: "/images/PartnerLogo/eClerx.png" },
    { id: 9, name: "Tikona", logo: "/images/PartnerLogo/Tikona.png" },
    { id: 10, name: "Reliance Industries Limited", logo: "/images/PartnerLogo/Reliance Industries Limited.png" },
    { id: 11, name: "IBM", logo: "/images/PartnerLogo/IBM.png" },
    { id: 12, name: "Capgemini", logo: "/images/PartnerLogo/Capgemini.png" },
    { id: 13, name: "TCS", logo: "/images/PartnerLogo/TCS.png" },
    { id: 14, name: "Tech Mahindra", logo: "/images/PartnerLogo/Tech Mahindra.png" },
    { id: 15, name: "Amazon", logo: "/images/PartnerLogo/Amazon.png" },
    { id: 16, name: "Infosys", logo: "/images/PartnerLogo/Infosys.png" },
    { id: 17, name: "Accenture", logo: "/images/PartnerLogo/Accenture.png" },
    { id: 18, name: "Adani", logo: "/images/PartnerLogo/Adani.png" },
    { id: 19, name: "Axis Bank", logo: "/images/PartnerLogo/Axis Bank.png" },
    { id: 20, name: "Oracle", logo: "/images/PartnerLogo/Oracle.png" },
    { id: 21, name: "Impact Infotech", logo: "/images/PartnerLogo/Impact Infotech.png" },
    { id: 22, name: "PBI Analytics", logo: "/images/PartnerLogo/PBI Analytics.png" },
    { id: 23, name: "MicroSense", logo: "/images/PartnerLogo/MicroSense.png" },
    { id: 24, name: "J.P. Morgan", logo: "/images/PartnerLogo/J.P. Morgan.png" },
    { id: 25, name: "Media.net", logo: "/images/PartnerLogo/Media.net.png" },
    { id: 26, name: "Cross Asyst", logo: "/images/PartnerLogo/Cross Asyst.png" },
    { id: 27, name: "PwC", logo: "/images/PartnerLogo/PwC.png" },
    { id: 28, name: "Lenovo", logo: "/images/PartnerLogo/Lenovo.png" },
    { id: 29, name: "Tata Elxsi", logo: "/images/PartnerLogo/Tata Elxsi.png" },
    { id: 30, name: "Huawei", logo: "/images/PartnerLogo/Huawei.png" },
    { id: 31, name: "Cognizant", logo: "/images/PartnerLogo/Cognizant.png" },
    { id: 32, name: "CMS IT Services", logo: "/images/PartnerLogo/CMS IT Services.png" },
    { id: 33, name: "Deloitte", logo: "/images/PartnerLogo/Deloitte.png" },
    { id: 34, name: "Quantech", logo: "/images/PartnerLogo/Quantech.png" },
    { id: 35, name: "Neural IT", logo: "/images/PartnerLogo/Neural IT.png" },
    { id: 36, name: "Infotech Solution", logo: "/images/PartnerLogo/Infotech Solution.png" },
    { id: 37, name: "iNurture", logo: "/images/PartnerLogo/iNurture.png" },
    { id: 38, name: "Adtech", logo: "/images/PartnerLogo/Adtech.png" },
    { id: 39, name: "Growfitter", logo: "/images/PartnerLogo/Growfitter.png" },
    { id: 40, name: "Osource", logo: "/images/PartnerLogo/Osource.png" },
    { id: 41, name: "V2S Tech Solutions", logo: "/images/PartnerLogo/V2S Tech Solutions.png" },
    { id: 42, name: "Saini Pati Shah & Co LLP", logo: "/images/PartnerLogo/Saini Pati Shah Co LLP.png" },
    { id: 43, name: "MAS", logo: "/images/PartnerLogo/MAS.png" },
    { id: 44, name: "Aditya Birla Group", logo: "/images/PartnerLogo/Aditya Birla Group.png" },
    { id: 45, name: "Ambisure", logo: "/images/PartnerLogo/Ambisure.png" },
    { id: 46, name: "Voitekk", logo: "/images/PartnerLogo/Voitekk.png" },
    { id: 47, name: "Supersonic", logo: "/images/PartnerLogo/Supersonic.png" },
    { id: 48, name: "Nividous", logo: "/images/PartnerLogo/Nividous.png" },
    { id: 49, name: "Step", logo: "/images/PartnerLogo/Step.png" },
    { id: 50, name: "Insight Business Machines Pvt Ltd", logo: "/images/PartnerLogo/Insight Business Machines Pvt Ltd.png" },
    { id: 51, name: "Genetics Cryobank", logo: "/images/PartnerLogo/Genetics Cryobank.png" },
    { id: 52, name: "CodeStudios", logo: "/images/PartnerLogo/CodeStudios.png" },
    { id: 53, name: "Thomas Baker Chemicals", logo: "/images/PartnerLogo/Thomas Baker Chemicals.png" },
    { id: 54, name: "TechAroha", logo: "/images/PartnerLogo/TechAroha.png" },
    { id: 55, name: "Slash RT", logo: "/images/PartnerLogo/Slash RT.png" },
    { id: 56, name: "Globetech", logo: "/images/PartnerLogo/Globetech.png" },
    { id: 57, name: "Scalix", logo: "/images/PartnerLogo/Scalix.png" },
    { id: 58, name: "Techno Purple", logo: "/images/PartnerLogo/Techno Purple.png" },
    { id: 59, name: "Paloli Technologies", logo: "/images/PartnerLogo/Paloli Technologies.png" },
    { id: 60, name: "Ghodan Technologies Pvt. Ltd", logo: "/images/PartnerLogo/Ghodan Technologies Pvt. Ltd.png" },
    { id: 61, name: "CBY", logo: "/images/PartnerLogo/CBY.png" },
    { id: 62, name: "76 Analytics", logo: "/images/PartnerLogo/76 Analytics.png" },
    { id: 63, name: "DMart", logo: "/images/PartnerLogo/DMart.png" },
    { id: 64, name: "ApMoSys", logo: "/images/PartnerLogo/ApMoSys.png" },
    { id: 65, name: "Saba Technosoft", logo: "/images/PartnerLogo/Saba Technosoft.png" },
    { id: 66, name: "Chemarc", logo: "/images/PartnerLogo/Chemarc.png" },
    { id: 67, name: "Zamin Private Limited", logo: "/images/PartnerLogo/Zamin Private Limited.gif" },
    { id: 68, name: "Advin Softwares", logo: "/images/PartnerLogo/Advin Softwares.png" },
    { id: 69, name: "Kirin Advisors", logo: "/images/PartnerLogo/Kirin Advisors.png" },
    { id: 70, name: "Textronics", logo: "/images/PartnerLogo/Textronics.png" },
    { id: 71, name: "qSEAp", logo: "/images/PartnerLogo/qSEAp.png" },
    { id: 72, name: "LivingThings", logo: "/images/PartnerLogo/LivingThings.png" },
    { id: 73, name: "Essenzaa", logo: "/images/PartnerLogo/Essenzaa.webp" },
    { id: 74, name: "Softcell", logo: "/images/PartnerLogo/Softcell.webp" },
    { id: 75, name: "Fyntune", logo: "/images/PartnerLogo/Fyntune.png" },
    { id: 76, name: "Credence Analytics", logo: "/images/PartnerLogo/Credence Analytics.png" },
    { id: 77, name: "Telex Advertising Agency", logo: "/images/PartnerLogo/Telex Advertising Agency.png" },
    { id: 78, name: "CancerMitr", logo: "/images/PartnerLogo/CancerMitr.png" },
    { id: 79, name: "Fernotech", logo: "/images/PartnerLogo/Fernotech.png" },
    { id: 80, name: "Modern Informatics", logo: "/images/PartnerLogo/Modern Informatics.png" },
    { id: 81, name: "Safari", logo: "/images/PartnerLogo/Safari.png" },
    { id: 82, name: "Naaptol", logo: "/images/PartnerLogo/Naaptol.png" },
    { id: 83, name: "KMW Advertising LLP", logo: "/images/PartnerLogo/KMW Advertising LLP.webp" },
    { id: 84, name: "Optilink", logo: "/images/PartnerLogo/Optilink.png" },
    { id: 85, name: "Nimap Infotech", logo: "/images/PartnerLogo/Nimap Infotech.svg" },
    { id: 86, name: "H Digital Media", logo: "/images/PartnerLogo/H Digital Media.webp" },
    { id: 87, name: "Mobilestyx", logo: "/images/PartnerLogo/Mobilestyx.png" },
    { id: 88, name: "Knowledge Solutions", logo: "/images/PartnerLogo/Knowledge Solutions.png" },
    { id: 89, name: "Stoosa", logo: "/images/PartnerLogo/Stoosa.png" },
    { id: 90, name: "NZ Seasonal Wear Pvt. Ltd.", logo: "/images/PartnerLogo/NZ Seasonal Wear Pvt. Ltd.png" },
    { id: 91, name: "Recollectix Media", logo: "/images/PartnerLogo/Recollectix Media.png" },
    { id: 92, name: "RRP S4E Innovation Pvt Ltd", logo: "/images/PartnerLogo/RRP S4E Innovation Pvt Ltd.png" },
    { id: 93, name: "Andro Apps Technologies", logo: "/images/PartnerLogo/Andro Apps Technologies.png" },
    { id: 94, name: "Sahasrara Meterech Pvt. Ltd.", logo: "/images/PartnerLogo/Sahasrara Meterech Pvt. Ltd.svg" },
    { id: 95, name: "Kubic Technology", logo: "/images/PartnerLogo/Kubic Technology.png" },
    { id: 96, name: "Velox", logo: "/images/PartnerLogo/Velox.png" },
    { id: 97, name: "Anzen", logo: "/images/PartnerLogo/Anzen.png" },
    { id: 98, name: "abylle", logo: "/images/PartnerLogo/abylle.png" }
];

export default partnerslogo;
